export default {
    price1:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`Starter`,
        usd:`USD`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`Business`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 100 ideas`,
        xx_teams:`1 team`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price2:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`Starter`,
        usd:`USD`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`PROFESSIONAL`,
        business:`Business`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 500 ideas`,
        xx_teams:`5 team(s)`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price3:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`Starter`,
        usd:`USD`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`BUSINESS`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 1000 ideas`,
        xx_teams:`10 team(s)`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price4:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`Starter`,
        usd:`USD`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`Business`,
        enterprise:`ENTERPRISE`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Unlimited ideas`,
        xx_teams:`Unlimited teams`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      }
}