export default {
  GB:{
    price1:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`STARTER`,
        usd:`USD`,
        currency:"$",
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`Business`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 100 ideas`,
        xx_teams:`1 team`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price2:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`STARTER`,
        most_popular:"Most Popular",
        usd:`USD`,
        currency:"$",
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`PROFESSIONAL`,
        business:`Business`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 500 ideas`,
        xx_teams:`5 team(s)`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price3:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`STARTER`,
        usd:`USD`,
        currency:"$",
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`BUSINESS`,
        enterprise:`Enterprise`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Up to 1000 ideas`,
        xx_teams:`10 team(s)`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      },
      price4:{
        plans_pricing:`Plans & Pricing`,
        choose_plan:`Choose the plan that best suits your needs. Don’t know which one to choose? Contact us.`,
        starter:`STARTER`,
        usd:`USD`,
        currency:"$",
        99:`99`,
        499:`499`,
        999:`999`,
        month:`Month`,
        professional:`Professional`,
        business:`Business`,
        enterprise:`ENTERPRISE`,
        for_pricing_custom:`For pricing and custom`,
        for_custom:`For pricing and custom features `,
        unlimited_members:`Unlimited members`,
        upto_xxx:`Unlimited ideas`,
        xx_teams:`Unlimited teams`,
        your_own_workspace:`Your own workspace for innovation`,
        collect_analyse:`Collect, analyze, and manage ideas`,
        performance_analytics:`Performance analytics on innovation and people`,
        advanced_audience:`Advanced audience segmentation`,
        custom_branding:`Customization according to your own branding`,
        single_sign_on:`Single-Sign-On`,
        dedicated_manager:`A dedicated innovation success manager`,
        sla_tech:`99.99% uptime SLA and technical support`,
        try_for_free:`Try it for free`,
        contact_us:`contact us`,
        faq:`Frequently Asked Questions`,
        can_i_cancel:`Can I cancel my subscription?`,
        our_goal:`Our goal is to make you happy. You can cancel at any time and won't be billed for subsequent months. `,
        payment_options:`What are my payment options?`,
        payments_made_via:`All payments are made via bank transfer. We will issue you invoices for payment. `,
        data_protection:`How is my data protected? `,
        serious_secutiry:`We take security very seriously. Your contact info, ideas and data are yours and yours alone. All data is encrypted using transport layer security. All ideas and content that you create and upload to the platform is only available to authenticated users. `,
        more_ides:`What happens if we collect more ideas than limited in the plan?`,
        dont_worry:`Don’t worry, we’ll let you know before you hit a limit so you can plan ahead. We facilitate Pay As You Grow - add 100 ideas for $99/month anytime.`,
        stay_in_touch:`Stay in touch if you have more questions`,
      }
    },
    CN:{
      price1:{
        plans_pricing:`价格方案`,
        choose_plan:`选择最适合企业需求的方案。如果您不知道该选择哪一个方案，请随时联系我们。`,
        starter:`基础版`,
        usd:` ¥`,
        currency:"¥",

        99:`699`,
        499:`3499`,
        999:`6999`,
        month:`每月`,
        professional:`专业版`,
        business:`商业版`,
        enterprise:`企业版`,
        for_pricing_custom:`联系我们获取报价和定制化功能`,
        for_custom:`联系我们获取报价和定制化功能`,
        unlimited_members:`无限用户`,
        upto_xxx:`最多100个创新想法`,
        xx_teams:`1个团队`,
        your_own_workspace:`企业独有的创新空间`,
        collect_analyse:`收集，分析和整理创新想法`,
        performance_analytics:`企业创新和员工创新数据分析`,
        advanced_audience:`先进的团队划分`,
        custom_branding:`根据企业的品牌形象定制`,
        single_sign_on:`单点登录（SSO）`,
        dedicated_manager:`专有创新成功专家支持`,
        sla_tech:`99.99%的可用时间保证和技术支持`,
        try_for_free:`免费试用`,
        contact_us:`联系我们`,
        faq:`常见问题`,
        can_i_cancel:`能否随时取消订阅？`,
        our_goal:`我们的目标是让您满意。您可以随时取消订阅，我们将从下月起取消对您的收费。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通过银行转账进行，我们将每月为您开具发票。`,
        data_protection:`你们怎样保护数据安全？`,
        serious_secutiry:`我们非常重视数据安全。您的联系方式，创新想法和数据都是您自己的。您在我们平台上创建的所有创新想法和提交的所有内容都只对经过验证的用户开放。所有数据都通过传输层安全性协定进行加密。`,
        more_ides:`如果我们提交的创新想法数超过价格方案中的数量怎么办？`,
        dont_worry:`不用担心，我们将在您达到限额前通知您。我们支持即用即付 - 您可以随时付额外的699元以增加100个创新想法。`,
        stay_in_touch:`如果您还有其他问题，请随时与我们联系`,
      },
      price2:{
        plans_pricing:`价格方案`,
        choose_plan:`选择最适合企业需求的方案。如果您不知道该选择哪一个方案，请随时联系我们。`,
        starter:`基础版`,
        most_popular:"最受欢迎",
        usd:`¥`,
        currency:"¥",

        99:`699`,
        499:`3499`,
        999:`6999`,
        month:`每月`,
        professional:`专业版`,
        business:`商业版`,
        enterprise:`企业版`,
        for_pricing_custom:`联系我们获取报价和定制化功能`,
        for_custom:`联系我们获取报价和定制化功能`,
        unlimited_members:`无限用户`,
        upto_xxx:`最多500个创新想法`,
        xx_teams:`5个团队`,
        your_own_workspace:`企业独有的创新空间`,
        collect_analyse:`收集，分析和整理创新想法`,
        performance_analytics:`企业创新和员工创新数据分析`,
        advanced_audience:`先进的团队划分`,
        custom_branding:`根据企业的品牌形象定制`,
        single_sign_on:`单点登录（SSO）`,
        dedicated_manager:`专有创新成功专家支持`,
        sla_tech:`99.99%的可用时间保证和技术支持`,
        try_for_free:`免费试用`,
        contact_us:`联系我们`,
        faq:`常见问题`,
        can_i_cancel:`能否随时取消订阅？`,
        our_goal:`我们的目标是让您满意。您可以随时取消订阅，我们将从下月起取消对您的收费。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通过银行转账进行，我们将每月为您开具发票。`,
        data_protection:`你们怎样保护数据安全？`,
        serious_secutiry:`我们非常重视数据安全。您的联系方式，创新想法和数据都是您自己的。您在我们平台上创建的所有创新想法和提交的所有内容都只对经过验证的用户开放。所有数据都通过传输层安全性协定进行加密。`,
        more_ides:`如果我们提交的创新想法数超过价格方案中的数量怎么办？`,
        dont_worry:`不用担心，我们将在您达到限额前通知您。我们支持即用即付 - 您可以随时付额外的699元以增加100个创新想法。`,
        stay_in_touch:`如果您还有其他问题，请随时与我们联系`,
      },
      price3:{
        plans_pricing:`价格方案`,
        choose_plan:`选择最适合企业需求的方案。如果您不知道该选择哪一个方案，请随时联系我们。`,
        starter:`基础版`,
        usd:`¥`,
        currency:"¥",

        99:`699`,
        499:`3499`,
        999:`6999`,
        month:`每月`,
        professional:`专业版`,
        business:`商业版`,
        enterprise:`企业版`,
        for_pricing_custom:`联系我们获取报价和定制化功能`,
        for_custom:`联系我们获取报价和定制化功能`,
        unlimited_members:`无限用户`,
        upto_xxx:`最多1000个创新想法`,
        xx_teams:`10个团队`,
        your_own_workspace:`企业独有的创新空间`,
        collect_analyse:`收集，分析和整理创新想法`,
        performance_analytics:`企业创新和员工创新数据分析`,
        advanced_audience:`先进的团队划分`,
        custom_branding:`根据企业的品牌形象定制`,
        single_sign_on:`单点登录（SSO）`,
        dedicated_manager:`专有创新成功专家支持`,
        sla_tech:`99.99%的可用时间保证和技术支持`,
        try_for_free:`免费试用`,
        contact_us:`联系我们`,
        faq:`常见问题`,
        can_i_cancel:`能否随时取消订阅？`,
        our_goal:`我们的目标是让您满意。您可以随时取消订阅，我们将从下月起取消对您的收费。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通过银行转账进行，我们将每月为您开具发票。`,
        data_protection:`你们怎样保护数据安全？`,
        serious_secutiry:`我们非常重视数据安全。您的联系方式，创新想法和数据都是您自己的。您在我们平台上创建的所有创新想法和提交的所有内容都只对经过验证的用户开放。所有数据都通过传输层安全性协定进行加密。`,
        more_ides:`如果我们提交的创新想法数超过价格方案中的数量怎么办？`,
        dont_worry:`不用担心，我们将在您达到限额前通知您。我们支持即用即付 - 您可以随时付额外的699元以增加100个创新想法。`,
        stay_in_touch:`如果您还有其他问题，请随时与我们联系`,
      },
      price4:{
        plans_pricing:`价格方案`,
        choose_plan:`选择最适合企业需求的方案。如果您不知道该选择哪一个方案，请随时联系我们。`,
        starter:`基础版`,
        usd:`¥`,
        currency:"¥",

        99:`699`,
        499:`3499`,
        999:`6999`,
        month:`每月`,
        professional:`专业版`,
        business:`商业版`,
        enterprise:`企业版`,
        for_pricing_custom:`联系我们获取报价和定制化功能`,
        for_custom:`联系我们获取报价和定制化功能`,
        unlimited_members:`无限用户`,
        upto_xxx:`无限的想法`,
        xx_teams:`无限的团队`,
        your_own_workspace:`企业独有的创新空间`,
        collect_analyse:`收集，分析和整理创新想法`,
        performance_analytics:`企业创新和员工创新数据分析`,
        advanced_audience:`先进的团队划分`,
        custom_branding:`根据企业的品牌形象定制`,
        single_sign_on:`单点登录（SSO）`,
        dedicated_manager:`专有创新成功专家支持`,
        sla_tech:`99.99%的可用时间保证和技术支持`,
        try_for_free:`免费试用`,
        contact_us:`联系我们`,
        faq:`常见问题`,
        can_i_cancel:`能否随时取消订阅？`,
        our_goal:`我们的目标是让您满意。您可以随时取消订阅，我们将从下月起取消对您的收费。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通过银行转账进行，我们将每月为您开具发票。`,
        data_protection:`你们怎样保护数据安全？`,
        serious_secutiry:`我们非常重视数据安全。您的联系方式，创新想法和数据都是您自己的。您在我们平台上创建的所有创新想法和提交的所有内容都只对经过验证的用户开放。所有数据都通过传输层安全性协定进行加密。`,
        more_ides:`如果我们提交的创新想法数超过价格方案中的数量怎么办？`,
        dont_worry:`不用担心，我们将在您达到限额前通知您。我们支持即用即付 - 您可以随时付额外的699元以增加100个创新想法。`,
        stay_in_touch:`如果您还有其他问题，请随时与我们联系`,
      }
    },
    HK:{
      price1:{
        plans_pricing:`價格方案`,
        choose_plan:`選擇最適合企業需求的方案。如果您不知道該選擇哪一個方案，請隨時聯繫我們。`,
        starter:`基礎版`,
        usd:`美元`,
        currency:"$",
        99:`99`,
        499:`499`,
        999:`999`,
        month:`每月`,
        professional:`專業版`,
        business:`商業版`,
        enterprise:`企業版`,
        for_pricing_custom:`聯絡我們獲取報價和定制化功能`,
        for_custom:`聯絡我們獲取報價和定制化功能`,
        unlimited_members:`無限用戶`,
        upto_xxx:`最多100個創新想法`,
        xx_teams:`1個團隊`,
        your_own_workspace:`企業獨有的創新空間`,
        collect_analyse:`收集，分析和整理創新想法`,
        performance_analytics:`企業創新和員工創新數據分析`,
        advanced_audience:`先進的團隊劃分`,
        custom_branding:`根據企業的品牌形象定制`,
        single_sign_on:`單一登入（SSO)`,
        dedicated_manager:`專有創新成功專家支持`,
        sla_tech:`99.99%的可用時間保證和技術支持`,
        try_for_free:`免費試用`,
        contact_us:`聯絡我們`,
        faq:`常見問題`,
        can_i_cancel:`能否隨時取消訂閱？`,
        our_goal:`我們的目標是讓您滿意。您可以隨時取消訂閱，我們將從下月起取消對您的收費。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通過銀行轉帳進行，我們將每月為您開具付款通知。`,
        data_protection:`你們怎樣保護數據安全？`,
        serious_secutiry:`我們非常重視數據安全。您的聯繫方式，創新想法和數據都是您自己的。您在我們平台上創建的所有創新想法和提交的所有內容都只對經過驗證的用戶開放。所有數據都通過傳輸層安全性協定進行加密。`,
        more_ides:`如果我們提交的創新想法數超過價格方案中的數量怎麼辦？`,
        dont_worry:`不用擔心，我們將在您達到限額前通知您。我們支持即用即付 - 您可以隨時付額外的99美元以增加100個創新想法。`,
        stay_in_touch:`如果您還有其他問題，請隨時與我們聯絡`,
      },
      price2:{
        plans_pricing:`價格方案`,
        choose_plan:`選擇最適合企業需求的方案。如果您不知道該選擇哪一個方案，請隨時聯繫我們。`,
        starter:`基礎版`,
        most_popular:"最受歡迎",
        usd:`美元`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`每月`,
        professional:`專業版`,
        business:`商業版`,
        enterprise:`企業版`,
        for_pricing_custom:`聯絡我們獲取報價和定制化功能`,
        for_custom:`聯絡我們獲取報價和定制化功能`,
        unlimited_members:`無限用戶`,
        upto_xxx:`最多500個創新想法`,
        xx_teams:`5個團隊`,
        your_own_workspace:`企業獨有的創新空間`,
        collect_analyse:`收集，分析和整理創新想法`,
        performance_analytics:`企業創新和員工創新數據分析`,
        advanced_audience:`先進的團隊劃分`,
        custom_branding:`根據企業的品牌形象定制`,
        single_sign_on:`單一登入（SSO)`,
        dedicated_manager:`專有創新成功專家支持`,
        sla_tech:`99.99%的可用時間保證和技術支持`,
        try_for_free:`免費試用`,
        contact_us:`聯絡我們`,
        faq:`常見問題`,
        can_i_cancel:`能否隨時取消訂閱？`,
        our_goal:`我們的目標是讓您滿意。您可以隨時取消訂閱，我們將從下月起取消對您的收費。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通過銀行轉帳進行，我們將每月為您開具付款通知。`,
        data_protection:`你們怎樣保護數據安全？`,
        serious_secutiry:`我們非常重視數據安全。您的聯繫方式，創新想法和數據都是您自己的。您在我們平台上創建的所有創新想法和提交的所有內容都只對經過驗證的用戶開放。所有數據都通過傳輸層安全性協定進行加密。`,
        more_ides:`如果我們提交的創新想法數超過價格方案中的數量怎麼辦？`,
        dont_worry:`不用擔心，我們將在您達到限額前通知您。我們支持即用即付 - 您可以隨時付額外的99美元以增加100個創新想法。`,
        stay_in_touch:`如果您還有其他問題，請隨時與我們聯絡`,
      },
      price3:{
        plans_pricing:`價格方案`,
        choose_plan:`選擇最適合企業需求的方案。如果您不知道該選擇哪一個方案，請隨時聯繫我們。`,
        starter:`基礎版`,
        usd:`美元`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`每月`,
        professional:`專業版`,
        business:`商業版`,
        enterprise:`企業版`,
        for_pricing_custom:`聯絡我們獲取報價和定制化功能`,
        for_custom:`聯絡我們獲取報價和定制化功能`,
        unlimited_members:`無限用戶`,
        upto_xxx:`最多1000個創新想法`,
        xx_teams:`10個團隊`,
        your_own_workspace:`企業獨有的創新空間`,
        collect_analyse:`收集，分析和整理創新想法`,
        performance_analytics:`企業創新和員工創新數據分析`,
        advanced_audience:`先進的團隊劃分`,
        custom_branding:`根據企業的品牌形象定制`,
        single_sign_on:`單一登入（SSO)`,
        dedicated_manager:`專有創新成功專家支持`,
        sla_tech:`99.99%的可用時間保證和技術支持`,
        try_for_free:`免費試用`,
        contact_us:`聯絡我們`,
        faq:`常見問題`,
        can_i_cancel:`能否隨時取消訂閱？`,
        our_goal:`我們的目標是讓您滿意。您可以隨時取消訂閱，我們將從下月起取消對您的收費。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通過銀行轉帳進行，我們將每月為您開具付款通知。`,
        data_protection:`你們怎樣保護數據安全？`,
        serious_secutiry:`我們非常重視數據安全。您的聯繫方式，創新想法和數據都是您自己的。您在我們平台上創建的所有創新想法和提交的所有內容都只對經過驗證的用戶開放。所有數據都通過傳輸層安全性協定進行加密。`,
        more_ides:`如果我們提交的創新想法數超過價格方案中的數量怎麼辦？`,
        dont_worry:`不用擔心，我們將在您達到限額前通知您。我們支持即用即付 - 您可以隨時付額外的99美元以增加100個創新想法。`,
        stay_in_touch:`如果您還有其他問題，請隨時與我們聯絡`,
      },
      price4:{
        plans_pricing:`價格方案`,
        choose_plan:`選擇最適合企業需求的方案。如果您不知道該選擇哪一個方案，請隨時聯繫我們。`,
        starter:`基礎版`,
        usd:`美元`,
        99:`99`,
        499:`499`,
        999:`999`,
        month:`每月`,
        professional:`專業版`,
        business:`商業版`,
        enterprise:`企業版`,
        for_pricing_custom:`聯絡我們獲取報價和定制化功能`,
        for_custom:`聯絡我們獲取報價和定制化功能`,
        unlimited_members:`無限用戶`,
        upto_xxx:`无限的想法`,
        xx_teams:`无限的团队`,
        your_own_workspace:`企業獨有的創新空間`,
        collect_analyse:`收集，分析和整理創新想法`,
        performance_analytics:`企業創新和員工創新數據分析`,
        advanced_audience:`先進的團隊劃分`,
        custom_branding:`根據企業的品牌形象定制`,
        single_sign_on:`單一登入（SSO)`,
        dedicated_manager:`專有創新成功專家支持`,
        sla_tech:`99.99%的可用時間保證和技術支持`,
        try_for_free:`免費試用`,
        contact_us:`聯絡我們`,
        faq:`常見問題`,
        can_i_cancel:`能否隨時取消訂閱？`,
        our_goal:`我們的目標是讓您滿意。您可以隨時取消訂閱，我們將從下月起取消對您的收費。`,
        payment_options:`付款方式有哪些？`,
        payments_made_via:`付款是通過銀行轉帳進行，我們將每月為您開具付款通知。`,
        data_protection:`你們怎樣保護數據安全？`,
        serious_secutiry:`我們非常重視數據安全。您的聯繫方式，創新想法和數據都是您自己的。您在我們平台上創建的所有創新想法和提交的所有內容都只對經過驗證的用戶開放。所有數據都通過傳輸層安全性協定進行加密。`,
        more_ides:`如果我們提交的創新想法數超過價格方案中的數量怎麼辦？`,
        dont_worry:`不用擔心，我們將在您達到限額前通知您。我們支持即用即付 - 您可以隨時付額外的99美元以增加100個創新想法。`,
        stay_in_touch:`如果您還有其他問題，請隨時與我們聯絡`,
      }
    }
}